# Generated by Django 3.1.3 on 2021-06-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('done', models.BooleanField()),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
